config/routes.rb
OnePagerApp::Application.routes.draw do
  
 
  resources :one_pagers

  get "search/search"
  get "search/search_result"

  
  get 'users/start'
  get 'users/register'
  get 'users/registered'
  get 'users/profile'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signup',  to: 'users#register',   via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :mig_users
  resources :mig_sessions, only: [:new, :create, :destroy]
  match '/mig_signup',  to: 'mig_users#new', via: 'get'
 

  resources :mig_sessions, only: [:new, :create, :destroy]
  match '/mig_signin',  to: 'mig_sessions#new',         via: 'get'
  match '/mig_signout', to: 'mig_sessions#destroy',     via: 'delete'
  match '/one_pager_approve',  to: 'one_pagers#one_pager_approve',  via: 'get'
  match '/mig_message/:id',  to: 'one_pagers#mig_message',  via: 'get'

  
  resources :apitest
  post 'apitest/patent', to: 'apitest#patent'
  post 'apitest/applicant', to: 'apitest#applicant'
  post 'apitest/portfolio', to: 'apitest#portfolio'
  post 'apitest/bulk', to: 'apitest#bulk'

  

end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { self.email = email.downcase }
  before_create :create_remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false },
            length: { maximum: 40 }

  has_secure_password
  validates :password, length: { maximum: 16, minimum: 6 }


  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def updateUserCounter
  end

  def allowedToCreateOnePager?
    if (self.blocked || !self.one_pager_allowed)
      false
    else
      true
    end
  end  

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end

end

app/controllers/users_controller.rb
require 'json'

class UsersController < ApplicationController

  def index
    #raise current_user.inspect
    #@user = current_user
    #puts JSON.pretty_generate(current_user.to_json)
  end

  def show
  end

  def new
    @user = User.new
  end

  def register
    @user = User.new
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      #flash[:success] = 'Welcome! You information has saved. You will receive a confirmation email with secure link.
      #                    After confirm you can access your account.'

      redirect_to action: 'registered'

    else
      render 'register'
    end
  end

  def registered

  end

  def profile

  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper

	# This function must return whether a user is signed in or not.
  #this function was implementaed in SessionHelper, so it's commented here
	#def signed_in?
		#Implementation pending
	#end

end

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/bak-index.html.erb
<div class="index-user-wrapper">
	<h2>If you wish to create an account <br> <%= link_to "Click Here", signup_path %></h2>
	<div class="row">
	    <div class="span6 offset3">
	      <%= form_for@user do |f| %>

	        <%= f.label :email %>
	        <%= f.text_field :email %>

	        <%= f.label :password %>
	        <%= f.password_field :password %>
	        
	        <%= label_tag :remember_me %>
    		<%= check_box_tag :remember_me, 1, params[:remember_me] %>
    		<br>

	        <%= f.submit "Sign in", class: "btn btn-primary" %>
	      <% end %>

	      
	    </div>
  </div>
</div>

app/views/users/bak-new.html.erb
<div class="new-user-wrapper">
	<h2>If you are a registered user <br> <%= link_to "Click Here", signin_path %></h2>
	<div class="row">
	  <div class="span6 offset3">
	    <%= form_for(@user) do |f| %>

		    <%= f.label :email %>
		    <%= f.text_field :email %>

	        <%= f.label :password %>
	  		<%= f.password_field :password %>

	  		<%= f.label :password_confirmation, "Confirmation" %>
	  		<%= f.password_field :password_confirmation %>

	     	<%= f.submit "Create my account", class: "btn btn-primary" %>
	    <% end %>

	    
	  </div>
	</div>


</div>

app/views/users/index.html.erb
<h1>Users#Index</h1>
<p>Here goes User Index page. Find me in app/views/users/index.html.erb</p>

<p>Hints: Is user signed in?</p>

<% if signed_in? %>
   <p> - Yes, <%=@current_user.email%> is signed in.</p>
   <p> - All information of logged in user: </p>
    <pre><%= @current_user.to_json(:only => [:email, :id, :confirmed, :blocked, :remember_token]) %></pre>
<% else %>
    - No, user is not signed in.
<% end %>

<p>For login <a href="/signin">click here</a></p>

<p>For Register <a href="/signup">click here</a></p>

<p>And logged in user <%= link_to "click here", signout_path, method: "delete" %> for logout.</p>

app/views/users/new.html.erb
<div class="new-user-wrapper">
	<h2>If you are a registered user <br> <%= link_to "Click Here", signin_path %></h2>
	<div class="row">
	  <div class="span6 offset3">
	    <%= form_for(@user) do |f| %>

		    <%= f.label :email %>
		    <%= f.text_field :email %>

	        <%= f.label :password %>
	  		<%= f.password_field :password %>

	  		<%= f.label :password_confirmation, "Confirmation" %>
	  		<%= f.password_field :password_confirmation %>

	     	<%= f.submit "Create my account", class: "btn btn-primary" %>
	    <% end %>

	    
	  </div>
	</div>


</div>

app/views/users/profile.html.erb
<div class="user-layout">
  <div>
    <span class="topmenu">Try it out!</span>
    <span class="topmenu highlight">Registered User</span>
    <span class="topmenu"><%= link_to "Sign out", signout_path, method: "delete" %></span>
  </div>
  <div class="body-part">
    <div class="title-top">
      <span class="title"> Profile </span>
    </div>
    <div class="middle-part">
      <p>Here goes user profile....</p>

      <span class="back-link"><a href="/users/">Go back to main screen</a> </span>

    </div>
  </div>
</div>

app/views/users/register.html.erb
<div class="user-layout">
  <div>
    <span class="topmenu">Try it out!</span>
    <span class="topmenu highlight">Registered User</span>
  </div>
  <div class="body-part">
    <div class="title-top">
        <span class="title"> Create Account </span>
    </div>
    <div class="middle-part">
        <p>If you are a registered user, <a href="/signin"> click here </a></p>

        <div class="form-part">
            <%= form_for :user, url: users_path do |f| %>
              <%= render 'error_messages' %>
               <p>
                 <%= f.label :email %>
                 <%= f.text_field :email %>
               </p>
               <p>
                 <%= f.label :password %>
                 <span><%= f.password_field :password %></span>
               </p>
               <p>
                 <%= f.label :password_confirmation, "Confirm Password" %>
                 <%= f.password_field :password_confirmation %>
               </p>
                  <%= f.submit "Create Account", class: "btn btn-large btn-primary" %>
            <% end %>
        </div>
    </div>
  </div>
</div>

app/views/users/registered.html.erb
<div class="user-layout">
  <div>
    <span class="topmenu">Try it out!</span>
    <span class="topmenu highlight">Registered User</span>
  </div>
  <div class="body-part">
    <div class="title-top">
        <span class="title"> Create Account </span>
    </div>
    <div class="middle-part">

      <div class="regsuccess-msg">
        <p>Thank you for registering! You should receive an email shortly
          with a link to confirm you registration.</p>

        <span class="back-link"><a href="/users/">Go back to main screen</a> </span>
      </div>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-layout">
  <div>
    <span class="topmenu">Try it out!</span>
    <span class="topmenu highlight">Registered User</span>
    <span class="topmenu"><%= link_to "Sign out", signout_path, method: "delete" %></span>
  </div>
  <div class="body-part">
    <div class="title-top">
        <span class="title"> Profile </span>
    </div>
    <div class="middle-part">
        <p>Here goes user profile....</p>


    </div>
  </div>
</div>

app/views/users/start.html.erb
<h1>Users#start</h1>
<p>Find me in app/views/users/start.html.erb</p>