config/routes.rb
OnePagerApp::Application.routes.draw do
  
 
  resources :one_pagers

  get "search/search"
  get "search/search_result"

  
  get 'users/start'
  get 'users/register'
  get 'users/registered'
  get 'users/profile'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signup',  to: 'users#register',   via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :mig_users
  resources :mig_sessions, only: [:new, :create, :destroy]
  match '/mig_signup',  to: 'mig_users#new', via: 'get'
 

  resources :mig_sessions, only: [:new, :create, :destroy]
  match '/mig_signin',  to: 'mig_sessions#new',         via: 'get'
  match '/mig_signout', to: 'mig_sessions#destroy',     via: 'delete'
  match '/one_pager_approve',  to: 'one_pagers#one_pager_approve',  via: 'get'
  match '/mig_message/:id',  to: 'one_pagers#mig_message',  via: 'get'

  
  resources :apitest
  post 'apitest/patent', to: 'apitest#patent'
  post 'apitest/applicant', to: 'apitest#applicant'
  post 'apitest/portfolio', to: 'apitest#portfolio'
  post 'apitest/bulk', to: 'apitest#bulk'

  

end

app/controllers/mig_sessions_controller.rb
class MigSessionsController < ApplicationController
  def new
  end

  def create
     @mig_user = MigUser.find_by(email: params[:mig_session][:email].downcase)
    if  @mig_user &&  @mig_user.authenticate(params[:mig_session][:password])
      mig_sign_in @mig_user
      redirect_to  one_pager_approve_path
    else
      flash.now[:error] = 'Wrong email or password !!! please try again'
      render 'new'
    end
  end
end

app/helpers/mig_sessions_helper.rb
module MigSessionsHelper

  def mig_sign_in(mig_user)
     remember_token = MigUser.new_remember_token
    if params[:mig_session][:remember_me]
      cookies.permanent[:remember_token] = remember_token	
   else
      cookies[:remember_token] = remember_token	 
    end
    mig_user.update_attribute(:remember_token, MigUser.encrypt(remember_token))
    self.mig_current_user = mig_user
  end

  def mig_signed_in?
    !mig_current_user.nil?
  end

  def mig_current_user=(mig_user)
    @mig_current_user = mig_user
  end

  def mig_current_user
    remember_token = MigUser.encrypt(cookies[:remember_token])
    @mig_current_user ||= MigUser.find_by(remember_token: remember_token)if cookies[:remember_token]
  end
  def mig_sign_out
    self.mig_current_user = nil
    cookies.delete(:remember_token)
  end
   def mig_signed_in_user
      redirect_to mig_signin_url, notice: "Please sign in." unless mig_signed_in?
    end

    def mig_correct_user
      @mig_user = MigUser.find(params[:id])
      redirect_to(root_url) unless mig_current_user?(@mig_user)
    end
    def destroy
    	mig_sign_out
    	flash[:notice] = "Successfully Signout."
    	redirect_to mig_signin_path and return
    end
end

app/views/mig_sessions/new.html.erb
<div class="user-layout">

  <div class="body-part">
    <div class="title-top">
        <span class="title"> MIG Log In </span>
    </div>
    <div class="middle-part">

        <div class="form-part">
            <%= form_for(:mig_session, url: mig_sessions_path) do |f| %>
              <% flash.each do |key, value| %>
                  <div class="alert alert-<%= key %>"><%= value %></div>
              <% end %>
              <p>
                 <%= f.label :email %>
                 <%= f.text_field :email, :placeholder => "Please Enter Email" %>
               </p>
               <p>
                 <%= f.label :password %>
                 <span><%= f.password_field :password, :placeholder => "Please Enter Password" %></span>
               </p>
		<p><%= f.check_box :remember_me, class: "remember_me" %> Remember me</p>
                <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
            <% end %>
        </div>
    </div>
  </div>
</div>