config/routes.rb
OnePagerApp::Application.routes.draw do
  
 
  resources :one_pagers

  get "search/search"
  get "search/search_result"

  
  get 'users/start'
  get 'users/register'
  get 'users/registered'
  get 'users/profile'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signup',  to: 'users#register',   via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :mig_users
  resources :mig_sessions, only: [:new, :create, :destroy]
  match '/mig_signup',  to: 'mig_users#new', via: 'get'
 

  resources :mig_sessions, only: [:new, :create, :destroy]
  match '/mig_signin',  to: 'mig_sessions#new',         via: 'get'
  match '/mig_signout', to: 'mig_sessions#destroy',     via: 'delete'
  match '/one_pager_approve',  to: 'one_pagers#one_pager_approve',  via: 'get'
  match '/mig_message/:id',  to: 'one_pagers#mig_message',  via: 'get'

  
  resources :apitest
  post 'apitest/patent', to: 'apitest#patent'
  post 'apitest/applicant', to: 'apitest#applicant'
  post 'apitest/portfolio', to: 'apitest#portfolio'
  post 'apitest/bulk', to: 'apitest#bulk'

  

end

app/models/one_pager.rb
class OnePager < ActiveRecord::Base
  has_and_belongs_to_many :one_pagers_tags
  has_one :one_pagers_patent_num
  belongs_to :mig_users
  belongs_to :users
  belongs_to :anonymous_users
  belongs_to :user_favorites
  self.inheritance_column = nil
	
	validates :patent_name, presence: true

	VALID_SINGLE_PATENT_NUM_REGEX = /\A(?:([A-Z]{2}(?:\d{7}|\d{11})[A-Z]\d))\z/

	validates :single_patent_num, presence: true, :if => :should_validate_single_patent_num? , format: { with: VALID_SINGLE_PATENT_NUM_REGEX }

	validates :company_name, presence: true, :if => :should_validate_company_name?

	#VALID_COMPANY_TAGS_LIST_REGEX = /(?:| , )([^,\s][^\,]*[^,\s]*)/
	VALID_COMPANY_TAGS_LIST_REGEX = /\A(?:(?:\A|\s*,\s*|\s*)([A-Za-z0-9_-]+)\b)+?\z/
	validates :tags_list, presence: true, :if => :should_validate_tags_list? , format: { with: VALID_COMPANY_TAGS_LIST_REGEX }
	
	VALID_PATENT_LIST_REGEX = /\A(?:(?:\A|\s*,\s*|\s*)([A-Z]{2}(?:\d{7}|\d{11})[A-Z]\d)\b)+?\z/
	validates :patent_list, presence: true, :if => :should_validate_patent_list? , format: { with: VALID_PATENT_LIST_REGEX }
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

	attr_accessor :email , :patent_list , :tags_list , :user_exists

	def should_validate_single_patent_num?
		type == "patent"
	end

	def should_validate_patent_list?
		type == "portfolio" || type == "patent_bulk"
	end	

	def should_validate_tags_list?
		type == "company_tags"
	end

	def should_validate_company_name?
		type == "company_tags"
	end

	def self.get_patent_one_pager(patent_number)
		OnePager.find_by_single_patent_num(patent_number)
	end

	def self.get_portfolio_one_pager(patents_list)
		patents_array = patents_list.split(/[^\w-]+/)
		patents_array.sort!
		patents_list = patents_array.join(',')
		one_pager_id = OnePagersPatentNum.group("one_pager_id").
						having("GROUP_CONCAT(patent_num ORDER BY patent_num ASC SEPARATOR ',') = ?",patents_list).
						order(created_at: :desc).
						pluck(:one_pager_id).
						first
		puts one_pager_id
		if (one_pager_id.nil?)
			nil
		else
			OnePager.find(one_pager_id)
		end

	end

	def self.get_patent_bulk_one_pager(patents_list)
		patents_array = patents_list.split(/[^\w-]+/)
		patents_array.sort!
		patents_list = patents_array.join(',')
		one_pager_id = OnePagersPatentNum.group("one_pager_id").
						having("GROUP_CONCAT(patent_num ORDER BY patent_num ASC SEPARATOR ',') = ?",patents_list).
						order(created_at: :desc).
						pluck(:one_pager_id).
						first
		puts one_pager_id
		if (one_pager_id.nil?)
			nil
		else
			OnePager.find(one_pager_id)
		end

	end

	def self.get_company_tags_one_pager(tags_list,company_name)
		tags_array = tags_list.split(/[^\w-]+/)
		tags_array.sort!
		tags_list = tags_array.join(',')
		ids = OnePagersTag.group("one_pager_id").
						having("GROUP_CONCAT(tag ORDER BY tag ASC SEPARATOR ',') = ?",tags_list).
						order(created_at: :desc).
						pluck(:one_pager_id)
		one_pager_id = OnePager.where("company_name = ? ", company_name).where(id: ids).pluck(:id).first
		if (one_pager_id.nil?)
			nil
		else
			OnePager.find(one_pager_id)
		end
	end	

	def self.updateLinks(id,html_link,pdf_link,img_link)
		one_pager = OnePager.find(id)
		one_pager.update_attribute(:html_link, html_link)
		one_pager.update_attribute(:pdf_link, pdf_link)
		one_pager.update_attribute(:img_link, img_link)
	end

	def self.updateOnePagerName(id,onePagerNewName)
		one_pager = OnePager.find(id)
		one_pager.update_attribute(:patent_name, onePagerNewName)
	end

	def self.updateOnePagerMigStatus(id,newStatus)
		one_pager = OnePager.find(id)
		one_pager.update_attribute(:mig_status, newStatus)
	end

	def self.updateOnePagerCreatedStatus(id,newStatus)
		one_pager = OnePager.find(id)
		one_pager.update_attribute(:created_status, newStatus)
	end

	def self.updateOnePagerEmailStatus(id,newStatus)
		one_pager = OnePager.find(id)
		one_pager.update_attribute(:email_status, newStatus)
	end

	def self.updateOnePagerComments(id,comments)
		one_pager = OnePager.find(id)
		one_pager.update_attribute(:comments, comments)
	end

	def self.updateOnePagerDate(id,date)
		one_pager = OnePager.find(id)
		one_pager.update_attribute(:date, date)
	end

end

app/controllers/one_pagers_controller.rb
class OnePagersController < ApplicationController
	before_action :mig_signed_in_user, only: [:edit, :update,:mig_message]
	#before_action :correct_user,   only: [:edit, :update]
        MIG_EMAIL = "munichinnovationgmbh@gmail.com"
        
        def show
                puts "Entered show"
                @one_pager = OnePager.find(params[:id])
        end

        def new
                puts "new start"
                @one_pager = OnePager.new

                @type = params[:report]
                if @type == "patent"
                        # Might be removed
                else
                        # Pending for the rest types of one pagers
                end
                if @type.nil?
                        render 'index'
                end
                puts "new end"
        end

        def create
                puts "Create started"
                @type = type_param[:type]

                if user_exists_param[:user_exists] == "true"
                        puts "User exists"
                        registered_user = true
                        user = User.find_by_email(email_param[:email])
                else
                        puts "User does not exist"
                        registered_user = false
                        user = AnonymousUser.find_by_email(email_param[:email])
                end

                if user.nil? || user.allowedToCreateOnePager?
                        
                        if @type == "patent"
                                puts "one_pager is patent"
                                @one_pager = OnePager.new(one_pager_patent_params)

                                if @one_pager.valid?
                                        if user.nil?
                                                user = AnonymousUser.createAnonUser(@one_pager.email)
                                        end
                                        @existing_one_pager = OnePager.get_patent_one_pager(@one_pager.single_patent_num)
                                        if (!@existing_one_pager.nil?)
                                                puts "one_pager exists"
                                                user.updateUserCounter
                                                redirect_to @existing_one_pager
                                        else
                                                @one_pager.user_id = user.id
                                                @one_pager.mig_status = "Pending"
                                                @one_pager.created_status = false
                                                if @one_pager.save
                                                        puts "one_pager saved"
                                                        user.updateUserCounter
                                                        MigMailer.new_one_pager(MIG_EMAIL,request.host_with_port,@one_pager.id.to_s).deliver
                                                        redirect_to @one_pager
                                                else
                                                        puts "Cannot save one pager"
                                                        # TODO : Fail
                                                        render 'new'
                                                end
                                        end
                                else
                                        puts "One pager is not valid"
                                        # TODO : Fail
                                        render 'new'
                                end

                        elsif @type == "portfolio"
                                puts "one_pager is portfolio"
                                @one_pager = OnePager.new(one_pager_portfolio_params)

                                if @one_pager.valid?
                                        if user.nil?
                                                user = AnonymousUser.createAnonUser(@one_pager.email)
                                        end
                                        @existing_one_pager = OnePager.get_portfolio_one_pager(@one_pager.patent_list)
                                        if (!@existing_one_pager.nil?)
                                                puts "one_pager exists"
                                                user.updateUserCounter
                                                redirect_to @existing_one_pager
                                        else
                                                @one_pager.user_id = user.id
                                                @one_pager.mig_status = "Pending"
                                                @one_pager.created_status = false
                                                if @one_pager.save
                                                        save_patent_list(@one_pager.patent_list,@one_pager.id)
                                                        puts "one_pager saved"
                                                        user.updateUserCounter
                                                        MigMailer.new_one_pager(MIG_EMAIL,request.host_with_port,@one_pager.id.to_s).deliver
                                                        redirect_to @one_pager
                                                else
                                                        puts "Cannot save one pager"
                                                        # TODO : Fail
                                                        render 'new'
                                                end
                                        end
                                else
                                        puts "One pager is not valid"
                                        # TODO : Fail
                                        render 'new'
                                end

                        elsif @type == "patent_bulk"
                                puts "one_pager is patent_bulk"
                                @one_pager = OnePager.new(one_pager_patent_bulk_params)

                                if @one_pager.valid?
                                        if user.nil?
                                                user = AnonymousUser.createAnonUser(@one_pager.email)
                                        end
                                        @existing_one_pager = OnePager.get_patent_bulk_one_pager(@one_pager.patent_list)
                                        if (!@existing_one_pager.nil?)
                                                puts "one_pager exists"
                                                user.updateUserCounter
                                                redirect_to @existing_one_pager
                                        else
                                                @one_pager.user_id = user.id
                                                @one_pager.mig_status = "Pending"
                                                @one_pager.created_status = false
                                                if @one_pager.save
                                                        save_patent_list(@one_pager.patent_list,@one_pager.id)
                                                        puts "one_pager saved"
                                                        user.updateUserCounter
                                                        MigMailer.new_one_pager(MIG_EMAIL,request.host_with_port,@one_pager.id.to_s).deliver
                                                        redirect_to @one_pager
                                                else
                                                        puts "Cannot save one pager"
                                                        # TODO : Fail
                                                        render 'new'
                                                end
                                        end
                                else
                                        puts "One pager is not valid"
                                        # TODO : Fail
                                        render 'new'
                                end                        
                        
                        elsif @type == "company_tags"
                                puts "one_pager is company_tags"
                                @one_pager = OnePager.new(one_pager_company_tags_params)
                                if @one_pager.valid?
                                        if user.nil?
                                                user = AnonymousUser.createAnonUser(@one_pager.email)
                                        end
                                        @existing_one_pager = OnePager.get_company_tags_one_pager(@one_pager.tags_list,@one_pager.company_name)
                                        if (!@existing_one_pager.nil?)
                                                puts "one_pager exists"
                                                user.updateUserCounter
                                                redirect_to @existing_one_pager
                                        else
                                                @one_pager.user_id = user.id
                                                @one_pager.mig_status = "Pending"
                                                @one_pager.created_status = false
                                                if @one_pager.save
                                                        puts "one_pager saved"
                                                        user.updateUserCounter
                                                        MigMailer.new_one_pager(MIG_EMAIL,request.host_with_port,@one_pager.id.to_s).deliver

app/helpers/one_pagers_helper.rb
module OnePagersHelper
end

app/views/one_pagers/_company_tags.html.erb
<p style="color: lightskyblue;">Please indicate all the necessary information</p>
<div class="row">
  <div class="span6">
    <%= form_for(@one_pager) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

    	<%= f.label :'Report name: ' %>
  		<%= f.text_field :patent_name, :placeholder => "My Report" ,:class => "masterTooltip" , 
                          :title => "Provide the name for your report" %>

    	<%= f.label :'Company name: ' %>
  		<%= f.text_field :company_name, :placeholder => "Apple Inc." ,:class => "masterTooltip" , 
                          :title => "Provide the name of the company" %>                          

  		<%= f.label :'Company Tags (comma separated):' %>
  		<%= f.text_area :tags_list, :placeholder => "Mac,iPad" ,:class => "masterTooltip" , 
                          :title => "Provide the patent numbers for the one pager , each in one row separated with comma" %>

  		<% if !signed_in? %>

      		<%= f.label :'Your e-mail: ' %>
      		<%= f.text_field :email,:placeholder => "email@example.com" , :class => "masterTooltip" , 
                          :title => "Please introduce your e-mail for us to send the links to download the report" %>

      <% else %>

      <%= f.hidden_field :email, :value => current_user.email %>      

  		<% end %>

  		<%= f.hidden_field :type, :value => "company_tags"%>

     	<%= f.submit "Continue to step 3", class: "btn btn-primary"  %>
    <% end %>

    
  </div>
</div>

app/views/one_pagers/_company_tags_form.html.erb
<p style="color: lightskyblue;">Please indicate all the necessary information</p>
<div class="row">
  <div class="span6">
    <%= form_for(@one_pager) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

    	<%= f.label :'Report name: ' %>
  		<%= f.text_field :patent_name, :placeholder => "My Report" ,:class => "masterTooltip" , 
                          :title => "Provide the name for your report" %>

    	<%= f.label :'Company name: ' %>
  		<%= f.text_field :company_name, :placeholder => "Apple Inc." ,:class => "masterTooltip" , 
                          :title => "Provide the name of the company" %>                          

  		<%= f.label :'Company Tags (comma separated):' %>
  		<%= f.text_area :tags_list, :placeholder => "Mac,iPad" ,:class => "masterTooltip" , 
                          :title => "Provide the patent numbers for the one pager , each in one row separated with comma" %>

  		<% if !signed_in? %>

      		<%= f.label :'Your e-mail: ' %>
      		<%= f.text_field :email,:placeholder => "email@example.com" , :class => "masterTooltip" , 
                          :title => "Please introduce your e-mail for us to send the links to download the report" %>

          <%= f.hidden_field :user_exists, :value => "false" %>

      <% else %>

      <%= f.hidden_field :email, :value => current_user.email %>
      <%= f.hidden_field :user_exists, :value => "true" %>

  		<% end %>

  		<%= f.hidden_field :type, :value => "company_tags"%>

     	<%= f.submit "Continue to step 3", class: "btn btn-primary"  %>
    <% end %>

    
  </div>
</div>

app/views/one_pagers/_patent_bulk_form.html.erb
<p style="color: lightskyblue;">Please indicate all the necessary information to generate a patent bulk report</p>
<div class="row">
  <div class="span6">
    <%= form_for(@one_pager) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

    	<%= f.label :'Report name: ' %>
  		<%= f.text_field :patent_name, :placeholder => "My Patent Bulk" ,:class => "masterTooltip" , 
                          :title => "Provide the name for your report" %>

      <%= f.label :'Patent numbers (comma separated):' %>
      <%= f.text_area :patent_list, :placeholder => "US6174724B1, US20010002490A1" ,:class => "masterTooltip" , 
                          :title => "Provide the patent numbers for the one pager separated with comma" %>

      <% if !signed_in? %>

          <%= f.label :'Your e-mail: ' %>
          <%= f.text_field :email,:placeholder => "email@example.com" , :class => "masterTooltip" , 
                          :title => "Please introduce your e-mail for us to send the links to download the report" %>

          <%= f.hidden_field :user_exists, :value => "false" %>

      <% else %>

      <%= f.hidden_field :email, :value => current_user.email %>
      <%= f.hidden_field :user_exists, :value => "true" %>      

      <% end %>

  		<%= f.hidden_field :type, :value => "patent_bulk"%>

     	<%= f.submit "Continue to step 3", class: "btn btn-primary"  %>
    <% end %>

    
  </div>
</div>

app/views/one_pagers/_patent_bulk_result.html.erb
<table class="table table-striped">
	<tr>
	<td style="width:100px"><b>Name</b></td>
	<td><%=@one_pager.patent_name%></td>
	</tr>
	
	<tr>
	<td><b>Status</b></td>
	<% if (@one_pager.mig_status == "Approved") %>
	<td style = "color:green"><%=@one_pager.mig_status%></td>
	<% else %>
	<td style = "color:orange"><%=@one_pager.mig_status%></td>
	<% end %>
	</tr>

	<tr>
	<td><b>Type</b></td>
	<td>Patent Bulk</td>
	</tr>

	<tr>
	<td><b>Patents</b></td>
	<td><%= OnePagersPatentNum.get_patent_list(@one_pager.id)%></td>
	</tr>

</table>

app/views/one_pagers/_patent_form.html.erb
<p style="color: lightskyblue;">Please indicate all the necessary information</p>
<div class="row">
  <div class="span6">
    <%= form_for(@one_pager) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

    	<%= f.label :'Report name: ' %>
  		<%= f.text_field :patent_name, :placeholder => "My Report" ,:class => "masterTooltip" , 
                          :title => "Provide the name for your report" %>

  		<%= f.label :'Patent number: ' %>
  		<%= f.text_field :single_patent_num, :placeholder => "US 6128685" ,:class => "masterTooltip" , 
                          :title => "Provide the patent number for the one pager" %>

      <% if !signed_in? %>

          <%= f.label :'Your e-mail: ' %>
          <%= f.text_field :email,:placeholder => "email@example.com" , :class => "masterTooltip" , 
                          :title => "Please introduce your e-mail for us to send the links to download the report" %>

          <%= f.hidden_field :user_exists, :value => "false" %>

      <% else %>

      <%= f.hidden_field :email, :value => current_user.email %>
      <%= f.hidden_field :user_exists, :value => "true" %>     

      <% end %>

  		<%= f.hidden_field :type, :value => "patent"%>

     	<%= f.submit "Continue to step 3", class: "btn btn-primary"  %>
    <% end %>

    
  </div>
</div>

app/views/one_pagers/_patent_result.html.erb
<table class="table table-striped">
	<tr>
	<td style="width:100px"><b>Name</b></td>
	<td><%=@one_pager.patent_name%></td>
	</tr>
	
	<tr>
	<td><b>Status</b></td>
	<% if (@one_pager.mig_status == "Approved") %>
	<td style = "color:green"><%=@one_pager.mig_status%></td>
	<% else %>
	<td style = "color:orange"><%=@one_pager.mig_status%></td>
	<% end %>
	</tr>

	<tr>
	<td><b>Type</b></td>
	<td>Patent</td>
	</tr>

	<tr>
	<td><b>Patent</b></td>
	<td><%=@one_pager.single_patent_num%></td>
	</tr>

</table>

app/views/one_pagers/_portfolio.html.erb
<p style="color: lightskyblue;">Please indicate all the necessary information to generate a portfolio report</p>
<div class="row">
  <div class="span6">
    <%= form_for(@one_pager) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

    	<%= f.label :'Report name: ' %>
  		<%= f.text_field :patent_name, :placeholder => "My Portfolio" ,:class => "masterTooltip" , 
                          :title => "Provide the name for your report" %>

  		<%= f.label :'Patent numbers (comma separated):' %>
  		<%= f.text_area :patent_list, :placeholder => "US6174724B1, US20010002490A1" ,:class => "masterTooltip" , 
                          :title => "Provide the patent numbers for the one pager separated with comma" %>

      <% if !signed_in? %>

          <%= f.label :'Your e-mail: ' %>
          <%= f.text_field :email,:placeholder => "email@example.com" , :class => "masterTooltip" , 
                          :title => "Please introduce your e-mail for us to send the links to download the report" %>

      <% else %>

      <%= f.hidden_field :email, :value => current_user.email %>      

      <% end %>

  		<%= f.hidden_field :type, :value => "portfolio"%>

     	<%= f.submit "Continue to step 3", class: "btn btn-primary"  %>
    <% end %>

    
  </div>
</div>

app/views/one_pagers/_portfolio_result.html.erb
<table class="table table-striped">
	<tr>
	<td style="width:100px"><b>Name</b></td>
	<td><%=@one_pager.patent_name%></td>
	</tr>
	
	<tr>
	<td><b>Status</b></td>
	<% if (@one_pager.mig_status == "Approved") %>
	<td style = "color:green"><%=@one_pager.mig_status%></td>
	<% else %>
	<td style = "color:orange"><%=@one_pager.mig_status%></td>
	<% end %>
	</tr>

	<tr>
	<td><b>Type</b></td>
	<td>Portfolio</td>
	</tr>

	<tr>
	<td><b>Patents</b></td>
	<td><%= OnePagersPatentNum.get_patent_list(@one_pager.id)%></td>
	</tr>

</table>

app/views/one_pagers/company_tags.html.erb
<div class="company_tags-wrapper">
	<p>Find me in app/views/one_pager/company_tags.html.erb</p>
</div>

app/views/one_pagers/edit.html.erb
<div class="row">
<div class="user-layout">
  <div class="body-part">
	    <div class="title-top">
		<span class="title"> MIG Approval</span>
	    </div>
    <div class="middle-part">
	       <p style = "color:blue"> Patent Report Request :  <a href="/mig_signup"> Sign Up </a> 
		<%= link_to "Sign out", mig_signout_path, method: "delete" %> </p>
	<div class="row">
		<div class="span12 ">
			<div class="row-fluid offset0">
			    <div class="span4 "  style="padding-top: 15px;">
				<table class="table table-striped"  >
					<tr>
					<td><b>Name</b></td>
					<td><%=@one_pager.patent_name%></td>
					</tr>
	
					<tr>
					<td><b>Status</b></td>
					<% if (@one_pager.mig_status == "Approve") %>
					<td style = "color:green"><%=@one_pager.mig_status%></td>
					<% else %>
					<td style = "color:orange"><%=@one_pager.mig_status%></td>
					<% end %>
					</tr>

					<tr>
					<td><b>Type</b></td>
					<td><%=@one_pager.type%></td>
					</tr>

					<tr>
					<td><b>Patent</b></td>
					<td><%= OnePagersPatentNum.get_patent_list(@one_pager.id)%></td>
					</tr>

				</table> 
			    </div>
			 
			    <div class="span7 offset1">
				  <%= form_for(@one_pager) do |f| %>
				      <%= f.label :comments %>
				       <%= f.text_area :comments, :id => "message_area", :cols => 20, :rows => 5 %>
				      <div class="control-group">
					 <div class="controls">
					    <%= f.submit 'Approve' , class: "btn btn-success" %>
					    <%= f.submit 'Deny' , class: "btn btn-danger"%>  	
					  </div>
					</div>
				    <% end %>
			    </div>
			</div>
		    </div>
	</div>
    </div>
  </div>
 </div>
</div>

app/views/one_pagers/index.html.erb
<div class="one_pagers-wrapper">
	
	<div class="progbar navbar">
       <div class="navbar-inner" style="padding: 0;">
         <div class="container" >
           <ul class="nav" style="margin: 0; display: table; width: 100%;" >
             <li class="active" ><a href="#">Step1: Select Report</a><div /></li>
             <li ><a href="#">Step2: Introduce Information</a><div /></li>
             <li ><a href="#">Step3: Results</a><div /></li>
           </ul>
         </div>
       </div>
     </div>

  <div class ="container">
    <p style="color: lightskyblue;">Please select the report you wish to generate</p>

    <div class="span2">
    	<div class="btn-group-vertical" data-toggle="buttons-radio">
      <button id = "b1" type="button" class="btn btn-default" checked>Patent</button>
      <button id = "b2" type="button" class="btn btn-default">Company Tags</button>
      <button id = "b3" type="button" class="btn btn-default">Portfolio</button>
      <button id = "b4" type="button" class="btn btn-default">Patent Bulk</button>
    </div>
    </div>
    <div class="span2">
    	<img id="descImg" src="/Crystal_Clear.png">
    </div>
    <div class="span4">
    	<p id="descText"> test test </p>
    </div>
  </div>
  <div align="right">
      <%= link_to 'Continue to step number 2' , '/one_pagers/new?report=patent',id:"linkToType" %>
  </div>
</div>



<script type="text/javascript">
$(document).ready(function() {

	$("#descImg").attr('src','/temp1.jpg');
  $("#linkToType").attr('href','/one_pagers/new?report=patent');
	$("#descText").text("Description for Patent");

	$('#b1').click(function() {
   		$("#descImg").attr('src','/temp1.jpg');
      $("#linkToType").attr('href','/one_pagers/new?report=patent');
   		$("#descText").text("Description for Patent");
   });

	$('#b2').click(function() {
   		$("#descImg").attr('src','/temp2.jpg');
      $("#linkToType").attr('href','/one_pagers/new?report=company_tags');
   		$("#descText").text("Description for Company Tags");
   });

	$('#b3').click(function() {
   		$("#descImg").attr('src','/temp3.jpg');
      $("#linkToType").attr('href','/one_pagers/new?report=portfolio');
   		$("#descText").text("Description for Portfolio");
   });

	$('#b4').click(function() {
   		$("#descImg").attr('src','/temp4.jpg');
      $("#linkToType").attr('href','/one_pagers/new?report=patent_bulk');
   		$("#descText").text("Description for Patent Bulk");
   });




 });
</script>

app/views/one_pagers/one_pager_approve.html.erb
<div class="row">
  
 onepager..........approved-------------------------------------------rough

<div class="user-layout">
  <div class="body-part">
	    <div class="title-top">
		<span class="title"> Mig Approval</span>
	    </div>
    <div class="middle-part">
       <p style = "color:blue"> Patent Report Request :  <a href="/mig_signup"> Sign Up </a> 
	<%= link_to 'Edit', edit_one_pager_path(@one_pager) %></p>
<div class="row">
  <div class="span6">
<table class="table table-striped"  >
	<tr>
	<td style="width:100px"><b>Name</b></td>
	<td><%=@one_pager.patent_name%></td>
	</tr>
	
	<tr>
	<td><b>Status</b></td>
	<% if (@one_pager.mig_status == "Approve") %>
	<td style = "color:green"><%=@one_pager.mig_status%></td>
	<% else %>
	<td style = "color:orange"><%=@one_pager.mig_status%></td>
	<% end %>
	</tr>

	<tr>
	<td><b>Type</b></td>
	<td><%=@one_pager.type%></td>
	</tr>

	<tr>
	<td><b>Patent</b></td>
	<td><%= OnePagersPatentNum.get_patent_list(@one_pager.id)%></td>
	</tr>

</table> 



</div>
  </div>

    </div>
  </div>

</div>

app/views/one_pagers/portfolio.html.erb
<div class="portfolio-wrapper">
	<p>Find me in app/views/one_pager/portfolio.html.erb</p>
</div>